name: Deploy Vite + Tailwind to GitHub Pages

on:
  push:
    branches: [ main ]   
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true     
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Clones repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Installs Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18   # 

      # 3. Installing dependencies
      - name: Install dependencies
        run: npm install

      # 4. Compiling with Vite
      - name: Build project
        run: npm run build

      # 5. Publish dist on GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: joribavi
          user_email: github-actions[bot]@users.noreply.github.com

          publish_dir: ./dist


